name: RRUIComponents
options:
  bundleIdPrefix: com.rrui
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    tvOS: "15.0"
    watchOS: "8.0"
    visionOS: "1.0"

packages:
  RRFoundation:
    url: https://github.com/rirp53021/rr-swift-foundation.git
    majorVersion: 1.8.0

settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.rrui.rruicomponents
  PRODUCT_NAME: RRUIComponents
  SWIFT_VERSION: 5.9
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
  MACOSX_DEPLOYMENT_TARGET: 12.0
  TVOS_DEPLOYMENT_TARGET: 15.0
  WATCHOS_DEPLOYMENT_TARGET: 8.0
  XROS_DEPLOYMENT_TARGET: 1.0
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  SWIFT_COMPILATION_MODE: "singlefile"

targets:
  RRUIComponents:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/RRUIComponents
    dependencies:
      - package: RRFoundation
    settings:
      PRODUCT_NAME: RRUIComponents
      PRODUCT_BUNDLE_IDENTIFIER: com.rrui.rruicomponents
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      SWIFT_ENABLE_LIBRARY_EVOLUTION: true
      SWIFT_COMPILATION_MODE: "singlefile"
    info:
      path: Sources/RRUIComponents/Info.plist
      properties:
        CFBundleDisplayName: RRUIComponents
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: FMWK
        CFBundleShortVersionString: 1.2.2
        CFBundleVersion: 1

  RRUIComponentsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/RRUIComponentsTests
    dependencies:
      - target: RRUIComponents
    settings:
      PRODUCT_NAME: RRUIComponentsTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rrui.rruicomponents.tests
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RRUIComponents.framework/RRUIComponents"
      TEST_TARGET_NAME: RRUIComponents
    info:
      path: Tests/RRUIComponentsTests/Info.plist
      properties:
        CFBundleDisplayName: RRUIComponentsTests
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: 1.2.2
        CFBundleVersion: 1

schemes:
  RRUIComponents:
    build:
      targets:
        RRUIComponents: all
    test:
      targets:
        - RRUIComponentsTests
    run:
      config: Debug
