name: RRUIComponents
options:
  bundleIdPrefix: com.rrui
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    tvOS: "15.0"
    watchOS: "8.0"
    visionOS: "1.0"
  generateEmptyDirectories: true

packages:
  RRFoundation:
    url: https://github.com/rirp53021/rr-swift-foundation.git
    from: 1.9.0
    generateScheme: false

settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.rrui.rruicomponents
  PRODUCT_NAME: RRUIComponents
  SWIFT_VERSION: 6.0
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
  MACOSX_DEPLOYMENT_TARGET: 12.0
  TVOS_DEPLOYMENT_TARGET: 15.0
  WATCHOS_DEPLOYMENT_TARGET: 8.0
  XROS_DEPLOYMENT_TARGET: 1.0
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  SWIFT_COMPILATION_MODE: "wholemodule"

targets:
  RRUIComponents:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/RRUIComponents
        excludes:
          - "**/*.plist"
    dependencies:
      - package: RRFoundation
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rrui.rruicomponents
      PRODUCT_NAME: RRUIComponents
      CLANG_ENABLE_MODULES: "YES"
      SWIFT_INSTALL_OBJC_HEADER: "NO"
      BUILD_LIBRARY_FOR_DISTRIBUTION: "YES"
      SWIFT_ENABLE_LIBRARY_EVOLUTION: "YES"
      SWIFT_COMPILATION_MODE: "wholemodule"
      SKIP_INSTALL: "NO"
      DEFINES_MODULE: "YES"
      MACH_O_TYPE: mh_dylib
    info:
      path: Sources/RRUIComponents/Info.plist
      properties:
        CFBundleName: RRUIComponents
        CFBundleDisplayName: RRUIComponents
        CFBundleIdentifier: com.rrui.rruicomponents
        CFBundleVersion: "2.1.0"
        CFBundleShortVersionString: "2.1.0"
        CFBundlePackageType: FMWK
        CFBundleInfoDictionaryVersion: "6.0"

  RRUIComponentsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/RRUIComponentsTests
    dependencies:
      - target: RRUIComponents
    settings:
      PRODUCT_NAME: RRUIComponentsTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rrui.tests

schemes:
  RRUIComponents:
    build:
      targets:
        RRUIComponents: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - RRUIComponentsTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
